package com.aicommandcenter.ai.command.tools;

import com.aicommandcenter.ai.command.CommandArgs;
import com.aicommandcenter.ai.command.CommandIntent;
import com.aicommandcenter.ai.command.CommandTool;
import com.aicommandcenter.ai.command.ToolResult;
import com.aicommandcenter.common.enums.Priority;
import com.aicommandcenter.goal.dto.GoalRequest;
import com.aicommandcenter.goal.dto.GoalResponse;
import com.aicommandcenter.goal.entity.GoalStatus;
import com.aicommandcenter.goal.service.GoalService;
import com.aicommandcenter.task.dto.TaskRequest;
import com.aicommandcenter.task.dto.TaskResponse;
import com.aicommandcenter.task.entity.TaskStatus;
import com.aicommandcenter.task.service.TaskService;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * The flagship command: "Create a 14-day Java interview preparation plan."
 *
 * <p>It creates one goal plus a dated task per day, so the result is real, tracked work rather
 * than a wall of generated text. Each task is persisted through {@link TaskService}, which means
 * the plan immediately shows up in the dashboard, the task list and goal progress.</p>
 */
@Component
public class CreateGoalWithPlanTool implements CommandTool {

    /** Ordered phases of a generic skill-acquisition plan; reused cyclically for longer horizons. */
    private static final List<String> PHASES = List.of(
            "Fundamentals and core concepts",
            "Hands-on practice on the core stack",
            "Deep dive into the primary framework",
            "Database modelling and SQL practice",
            "Testing strategy: unit and integration",
            "Concurrency, performance and caching",
            "System design and scaling basics",
            "Security fundamentals and hardening",
            "Build, CI/CD and deployment",
            "Observability, logging and debugging",
            "Mock interview and timed problem solving",
            "Revision, gap analysis and weak-spot drill",
            "Portfolio project polish",
            "Final review and behavioural preparation");

    private final GoalService goalService;
    private final TaskService taskService;

    public CreateGoalWithPlanTool(GoalService goalService, TaskService taskService) {
        this.goalService = goalService;
        this.taskService = taskService;
    }

    @Override
    public CommandIntent intent() {
        return CommandIntent.CREATE_GOAL_WITH_PLAN;
    }

    @Override
    public Set<String> allowedArguments() {
        return CommandIntent.CREATE_GOAL_WITH_PLAN.arguments();
    }

    @Override
    public ToolResult execute(Long userId, CommandArgs args) {
        args.rejectUnknown(allowedArguments());
        String title = args.require("title", 180);
        int days = args.optionalInt("days", 14, 1, 180);
        String focus = args.optional("focus") == null ? title : args.optional("focus");
        LocalDate today = LocalDate.now();

        GoalRequest goalRequest = new GoalRequest(title, "Auto-generated plan: " + focus, today.plusDays(days),
                args.optionalPriority("priority") == null ? Priority.HIGH : args.optionalPriority("priority"),
                GoalStatus.ACTIVE, "Plan generated by the AI command bar over " + days + " days.");
        GoalResponse goal = goalService.create(userId, goalRequest);

        List<TaskResponse> tasks = new ArrayList<>(days);
        for (int day = 1; day <= days; day++) {
            String phase = PHASES.get((day - 1) % PHASES.size());
            String taskTitle = truncate(focus + " — " + phase + " (day " + day + " of " + days + ")", 180);
            TaskRequest request = new TaskRequest(
                    taskTitle,
                    "Day " + day + " of the " + days + "-day plan for \"" + focus + "\".",
                    TaskStatus.TODO,
                    day % 7 == 0 ? Priority.HIGH : Priority.MEDIUM,
                    today.plusDays(day),
                    goal.id(),
                    List.of("plan", "auto-generated"));
            tasks.add(taskService.create(userId, request));
        }

        List<String> steps = List.of(
                "Created goal \"" + goal.title() + "\"",
                "Created " + tasks.size() + " tasks (" + today.plusDays(1) + " → " + today.plusDays(days) + ")",
                "Generated a " + days + "-day study plan");

        Map<String, Object> data = new LinkedHashMap<>();
        data.put("goal", goal);
        data.put("tasks", tasks);
        data.put("days", days);
        return ToolResult.of("Created goal \"" + goal.title() + "\" with " + tasks.size() + " planned tasks",
                steps, data);
    }

    private static String truncate(String value, int max) {
        return value.length() <= max ? value : value.substring(0, max);
    }
}
