-- AI Command Center :: initial schema
-- Portable SQL: runs on H2 (MODE=PostgreSQL) and on PostgreSQL.

CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(160) NOT NULL,
    password_hash  VARCHAR(200) NOT NULL,
    display_name   VARCHAR(120) NOT NULL,
    headline       VARCHAR(200),
    enabled        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE user_skills (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    skill       VARCHAR(80) NOT NULL,
    level       VARCHAR(20) NOT NULL DEFAULT 'INTERMEDIATE',
    verified    BOOLEAN NOT NULL DEFAULT FALSE,
    source      VARCHAR(40) NOT NULL DEFAULT 'SELF_REPORTED',
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_skill_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_skill_user UNIQUE (user_id, skill)
);
CREATE INDEX ix_skill_user ON user_skills (user_id);

CREATE TABLE goals (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    title        VARCHAR(180) NOT NULL,
    description  TEXT,
    deadline     DATE,
    priority     VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    status       VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    notes        TEXT,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_goal_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX ix_goal_user_status ON goals (user_id, status);

CREATE TABLE tasks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    goal_id       BIGINT,
    title         VARCHAR(180) NOT NULL,
    description   TEXT,
    status        VARCHAR(20) NOT NULL DEFAULT 'TODO',
    priority      VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    due_date      DATE,
    tags          VARCHAR(300),
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at  TIMESTAMP,
    CONSTRAINT fk_task_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_goal FOREIGN KEY (goal_id) REFERENCES goals (id) ON DELETE SET NULL
);
CREATE INDEX ix_task_user_status ON tasks (user_id, status);
CREATE INDEX ix_task_user_due ON tasks (user_id, due_date);

CREATE TABLE documents (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    name            VARCHAR(255) NOT NULL,
    content_type    VARCHAR(120) NOT NULL,
    size_bytes      BIGINT NOT NULL,
    storage_path    VARCHAR(400) NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    extracted_chars INTEGER NOT NULL DEFAULT 0,
    failure_reason  VARCHAR(400),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_document_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX ix_document_user ON documents (user_id);

CREATE TABLE document_chunks (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id     BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,
    chunk_index     INTEGER NOT NULL,
    content         TEXT NOT NULL,
    embedding       TEXT NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chunk_document FOREIGN KEY (document_id) REFERENCES documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_chunk_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX ix_chunk_document ON document_chunks (document_id);
CREATE INDEX ix_chunk_user ON document_chunks (user_id);

CREATE TABLE job_analyses (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL,
    job_title          VARCHAR(200),
    company            VARCHAR(200),
    raw_description    TEXT NOT NULL,
    required_skills    TEXT,
    preferred_skills   TEXT,
    technologies       TEXT,
    experience         VARCHAR(200),
    education          VARCHAR(200),
    responsibilities   TEXT,
    match_score        INTEGER NOT NULL DEFAULT 0,
    gap_analysis       TEXT,
    interview_topics   TEXT,
    learning_plan      TEXT,
    interview_questions TEXT,
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_job_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX ix_job_user ON job_analyses (user_id);

CREATE TABLE research_reports (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    topic            VARCHAR(240) NOT NULL,
    overview         TEXT,
    key_findings     TEXT,
    concepts         TEXT,
    recommendations  TEXT,
    sources          TEXT,
    summary          TEXT,
    grounded         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_research_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX ix_research_user ON research_reports (user_id);

CREATE TABLE ai_activities (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    command         VARCHAR(600) NOT NULL,
    intent          VARCHAR(60) NOT NULL,
    status          VARCHAR(20) NOT NULL,
    result_summary  TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_activity_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX ix_activity_user ON ai_activities (user_id, created_at);

CREATE TABLE notifications (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    event_type   VARCHAR(40) NOT NULL,
    title        VARCHAR(200) NOT NULL,
    message      TEXT,
    is_read      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dedupe_key   VARCHAR(200) NOT NULL,
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_notification_dedupe UNIQUE (user_id, dedupe_key)
);
CREATE INDEX ix_notification_user ON notifications (user_id, is_read);
